// <auto-generated />
using System;
using CookbookApp.Model.CookbookApp.Model;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CookbookApp.Migrations
{
    [DbContext(typeof(RecipeContext))]
    partial class RecipeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CookbookApp.Model.CookbookApp.Model.AccessFrequency", b =>
                {
                    b.Property<int>("AccessfrequencyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("DateLastAccessed")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecipeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("TimesAccessed")
                        .HasColumnType("int");

                    b.HasKey("AccessfrequencyID");

                    b.HasIndex("RecipeID");

                    b.ToTable("accessFrequency");
                });

            modelBuilder.Entity("CookbookApp.Model.CookbookApp.Model.Recipe", b =>
                {
                    b.Property<string>("RecipeID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AppliedTagsTagID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateSaved")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("SavedRecipe")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("RecipeID");

                    b.HasIndex("AppliedTagsTagID");

                    b.HasIndex("UserID");

                    b.ToTable("Recipes");
                });

            modelBuilder.Entity("CookbookApp.Model.CookbookApp.Model.Tags", b =>
                {
                    b.Property<string>("TagID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("TagID");

                    b.ToTable("tags");
                });

            modelBuilder.Entity("CookbookApp.Model.CookbookApp.Model.User", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.HasKey("UserID");

                    b.ToTable("user");
                });

            modelBuilder.Entity("CookbookApp.Model.CookbookApp.Model.AccessFrequency", b =>
                {
                    b.HasOne("CookbookApp.Model.CookbookApp.Model.Recipe", "recipe")
                        .WithMany()
                        .HasForeignKey("RecipeID");
                });

            modelBuilder.Entity("CookbookApp.Model.CookbookApp.Model.Recipe", b =>
                {
                    b.HasOne("CookbookApp.Model.CookbookApp.Model.Tags", "AppliedTags")
                        .WithMany()
                        .HasForeignKey("AppliedTagsTagID");

                    b.HasOne("CookbookApp.Model.CookbookApp.Model.User", null)
                        .WithMany("Recipes")
                        .HasForeignKey("UserID");
                });
#pragma warning restore 612, 618
        }
    }
}
